notifications:
  email:
    recipients:
      - is419@ic.ac.uk
      - amaankahmad@gmail.com

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build || true
  - gem install faraday -v 1.9.3
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
#  - npm test

deploy:
  provider: heroku
  api_key: 4cf47c69-983c-476a-b952-734761af0640
  app: nhs-handover-app-frontend
  skip_cleanup: true